services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kara
      - POSTGRES_USER=postgres
    container_name: db-kara
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-kara
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  
  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
      - NGINX_HOST=159.223.36.142
      - NGINX_PORT=80

volumes:
  db-data: